### PR TITLE
Adds support for Kibana 7.3.2

### PR DESCRIPTION
**Pull request by dbbaughe**
*Issue #, if available:*

*Description of changes:*
Adds support for Kibana 7.3.2
Ran into issues with EuiIcon dynamic loading when using transitive Eui dependency from Kibana, so adding it as a hard dependency at last working version from Kibana 7.2.
Related issue: https://github.com/elastic/eui/issues/2530

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by gittygoo** [comment]
I'm getting 
`Plugin installation was unsuccessful due to error "Plugin opendistro_index_management_kibana [7.3.2] is incompatible with Kibana [7.2.0]"` so i'm guessing this is now only compatible with 7.3? Opendistro doesnt seem to have a release for 7.3 yet though.

**Comment by lucaswin-amzn** [comment]
Hi @gittygoo, to install 7.2.1 (we do not support 7.2.0), please use the opendistro-1.2 branch and not master if you are building it manually, otherwise you can download ODFE 1.2 from our page [here](https://opendistro.github.io/for-elasticsearch/downloads.html).

**Comment by gittygoo** [comment]
got it, so i'm assuming there is no release made for 7.2.1 either? Would it be possible to do one? Trying to pull it over a docker build so its quite handy to pull straight from the github releases here

**Comment by qreshi** [comment]
As @lucaswin-amzn mentioned, the ```opendistro-1.2``` branch is what you'll want to use for ES 7.2.x. The head of the ```opendistro-1.2``` branch in the Index Management Kibana repo is currently for ES 7.2.1 but ODFE does support both ES 7.2.0 and 7.2.1.

Using [the Docker images as an example](https://hub.docker.com/r/amazon/opendistro-for-elasticsearch/tags) here are some of the ODFE to ES mappings:

ODFE 0.10 -> ES 6.8.1
ODFE 1.2.0 -> ES 7.2.0
ODFE 1.2.1 -> ES 7.2.1

I did notice that there are no releases made for Index Management 1.2 (both the backend and Kibana plugin) which is likely causing the confusion of missing support for ES 7.2. I'll go ahead and create those shortly but you can also build them manually using the ```opendistro-1.2``` branches.

Hope that clears things up @gittygoo

**Comment by gittygoo** [comment]
@qreshi yes that clears it all up, i have already bumped my version to 7.2.1 but as you noted since there are no releases for it and i think they will be useful for others hence my request for them to be available (and also since im not so handy with yarn) :) So with the release for the 1.2 branch all will be great :) thanks for the amazingly quick replies

**Comment by rozmir** [comment]
Hello there,
Can someone help me please? I get this error:
**bin/kibana-plugin install index-management-kibana-plugin-opendistro-1.2.zip --allow-root**
### Attempting to transfer from index-management-kibana-plugin-opendistro-1.2.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/index-management-kibana-plugin-opendistro-1.2.zip/index-management-kibana-plugin-opendistro-1.2.zip-7.2.1.zip
Plugin installation was unsuccessful due to error "No valid url specified."

**Comment by qreshi** [comment]
Hey @rozmir,

You'll want to prepend ```file://``` to the path of your zip when installing with a file. So it will look like:
```bin/kibana-plugin install file:///some//path/my-plugin.zip```.

**Comment by rozmir** [comment]
Thanks a lot for the reply, it is in the same dir and now I gave the path but still the same.
bin/kibana-plugin install --allow-root ./index-management-kibana-plugin-opendistro-1.2.zip
Attempting to transfer from ./index-management-kibana-plugin-opendistro-1.2.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/./index-management-kibana-plugin-opendistro-1.2.zip/./index-management-kibana-plugin-opendistro-1.2.zip-7.2.1.zip
Plugin installation was unsuccessful due to error "No valid url specified."

**Comment by rozmir** [comment]
Hello @qreshi ,
Thank you so much for the reply. I get this error now:
bin/kibana-plugin install --allow-root file:./index-management-kibana-plugin-opendistro-1.2.zip
Attempting to transfer from file:./index-management-kibana-plugin-opendistro-1.2.zip
Transferring 337716 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

**Comment by gittygoo** [comment]
any luck on creating the releases for 7.2.1 @qreshi  ?

**Comment by rozmir** [comment]
I need this plugin to keep the indices files for limited time only (ex. 2 days) as they grow quickly. Is this plugin the only solution or if anyone knows other ways to do it please? Thanks a lot!

**Comment by qreshi** [comment]
Sorry about that @gittygoo and @rozmir, we ran into an issue with Index Management Kibana for 7.2.1 and are currently looking into it. We'll have the releases updated after this is resolved.

**Comment by gittygoo** [comment]
Thats ok @qreshi, on a side note, maybe its good that we open another issue for that? to not be writting always on this somewhat unrelated issue. Should i go ahead and create one or will you ?

**Comment by rozmir** [comment]
Thanks @qreshi . Now I removed the plugin from plugins folder but Kibana doesn't come up anymore. Do I need to re-install it? If so, can you give me the instructions please? Also, is there any other way to purge the indies for now?
Thanks a lot!

**Comment by jinsoor-amzn** [comment]
@rozmir Can you please create a separate issues for problem you are seeing. This PR is not a good place to track and communicate the problem you are facing.

Thank you!

**Pull request merged**
